version: '3.4'

services:
  web-api:
    image: web-api
    container_name: web-api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    depends_on:
      - rabbitmq
      - redis
    links:
      - rabbitmq
      - redis
  

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"   # Default RabbitMQ Port
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  redis:
    image: redis:7.2.5
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    # # volumes:
    # #   - /path/to/local/dаta:/root/redis
    # #   - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
